### ISSUE TITLE
Equals Sign when using cmd.run leads to kwargs usage

### ISSUE THREAD

**Issue by chforster** [jenkinsci/saltstack-plugin#102]
Using saltstack-plugin Version 3.1.1 I have the following problem:
I use cmd.run to pass docker arguments to my salt minions.

Using 
`salt authtype: 'pam', clientInterface: local(arguments: "'docker stop myctnr'", function: 'cmd.run', target: "my.minion", targettype: 'glob'), credentialsId: 'saltmaster', saveFile: true, servername: "https://mysaltmaster:8000"
`
leads to the following _correct_ output:
`Sending JSON: {"client":"local","tgt":"my.minion","expr_form":"glob","fun":"cmd.run","arg":"docker stop myctnr","kwarg":{}`

If I want to remove dangling Images I have the following behaviour:

Using
`salt authtype: 'pam', clientInterface: local(arguments: "'docker rmi \$(docker images -f \"dangling=true\" -q)'", function: 'cmd.run', target: "my.minion", targettype: 'glob'), credentialsId: 'saltmaster', saveFile: true, servername: "https://mysaltmaster:8000"
`

leads to 
`Sending JSON: {"client":"local","tgt":"my.minion","expr_form":"glob","fun":"cmd.run","kwarg":{"docker rmi $(docker images -f \"dangling":"true\" -q)"}}`

Why will the arguments be transformed to kwargs when using "dangling=true"? Can this be prevented?

**Comment by mchugh19** [comment]
Indeedy. I'll take a look

**Comment by mchugh19** [comment]
Just uploaded a build intended to correct this. Can you please test https://github.com/jenkinsci/saltstack-plugin/releases/tag/3.1.2-beta1

**Comment by chforster** [comment]
Looks good: 

```
Sending JSON: {"client":"local","tgt":"my.minion","expr_form":"glob","fun":"cmd.run","arg":"docker rmi $(docker images -f \"dangling=true\" -q)","kwarg":{}}
```
