### ISSUE TITLE
Plugin fails to call state.orchestrate after salt upgrade to 2017.7.1

### ISSUE THREAD

**Issue by rbjorklin** [jenkinsci/saltstack-plugin#105]
We were running 2016.11.3 together with the saltstack-plugin 3.1.2 successfully but after upgrading to 2017.7.1 the plugin fails with the below error. The exact same command works when used on the command line which makes me think this is either a problem in the plugin or in the salt-api.

    Sep 20, 2017 1:42:51 PM FINE com.waytta.saltstack
    Discovered netapi: CherryPy/5.6.0

    Sep 20, 2017 1:42:51 PM FINE com.waytta.saltstack
    Sending JSON: {"client":"runner","mods":" orch.app.host-upgrade","pillar":{"data":{"organization":"example","cluster":"purple-nightly","version":"LATEST","upgradeManager":true}},"fun":"state.orchestrate"}

    Sep 20, 2017 1:42:53 PM FINE com.waytta.saltstack
    Received response: [{"outputter":"highstate","data":{"salt.dev.example.com_master":["No matching sls found for ' orch.app.host-upgrade' in env 'base'"]},"retcode":1}]

**Comment by mchugh19** [comment]
Gotcha. Seems this is related to the orchestration changes mentioned in saltstack/salt#42632. It seems there isn't a method for querying the salt-api version in use to allow for coordinating JSON sent with API expectation saltstack/salt#42491 making it difficult to support both pre and post 2017. 

Maybe this could be handled with a manual version selection of the salt-api.

**Comment by rbjorklin** [comment]
Manual version selection would be fine for me!

**Comment by rbjorklin** [comment]
So... I've managed to get this to work and it seems my initial analysis was incorrect. If you look closely at the posted JSON you can spot a leading space in the value for `mods`. That was always there but it seems 2017.7.1 is stricter.

Closing this issue as it seems to have been [PEBCAK](https://en.wikipedia.org/wiki/User_error#PEBKAC).

**Comment by mchugh19** [comment]
Fantastic! Thanks for the update!
