### ISSUE TITLE
Issue using credentials with "SSH username with private key"

### ISSUE THREAD

**Issue by anitakrueger** [jenkinsci/saltstack-plugin#108]
I'm trying to connect to my Salt api using credentials that I have already saved in Jenkins. It's a username with an SSH private key. However, the credential does not show up in the drop down list (the only entry in there is the only credential I have with username/password). So I am trying to add a new credential which never shows up in there either.
Am I missing some configuration?

Thanks a lot for your help! Desperate to get this Jenkins/Salt integration going :)

**Comment by anitakrueger** [comment]
I have also tried to create the job from a config xml manually specifying my credentials ID in there. When I do that, the job gets created successfully, however when I go on to configure it to test the connection to the Salt API, I get a red error message under the credential drop down box saying this:
```
Cannot find any credentials with id MYCREDENTIALSID
```

**Comment by mchugh19** [comment]
This plugin interacts with the salt-api, which uses username and password, not ssh. Hence the requirement that you use credentials with username and password. This previously came up in issue #16, so I'll add a blurb about it to the docs on the wiki.

**Comment by anitakrueger** [comment]
Christian, I feel stupid now. Should've found that other github issue as well.
Of course everything works with username/password authentication. Not using a password is so engrained in me now...tsss...

**Comment by mchugh19** [comment]
No problem! Happy to help, sorry for the stupid feelings ;)
