### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by webmailcontatos** [jenkinsci/saltstack-plugin#112]
I know that here is not the appropriate place for this type of question but I did not find the place on the internet
most appropriate.

What unit of measure is the completion of variable duration?

microsecond, millisecond, second ..

"duration": 6743.466,

**Comment by mchugh19** [comment]
It appears salt uses miliseconds as the base unit.

Looks like the highstate output formatter takes ms as input and calculates the human readable version. See https://github.com/saltstack/salt/blob/develop/salt/output/highstate.py#L462
