### ISSUE TITLE
"Abort If Incomplete" Support ?

### ISSUE THREAD

**Issue by chrisLeeTW** [jenkinsci/saltstack-plugin#113]
Hello,

Is there any plan to add a support for abort if minion incomplete  behavior, just like saltstack pepper does. (https://github.com/saltstack/pepper)

Thanks :)

**Comment by mchugh19** [comment]
Looks like the pepper function "Returns a failure exit code if not all minions respond". This sounds like the existing functionality of the minion timeout option as discussed #59. With the current implementation of timeout, if a salt message is sent, some minions return but not all, you can specify a timeout after which jenkins will fail the build.

What is the desired behavior?

**Comment by chrisLeeTW** [comment]
@mchugh19 sorry, I am misunderstand the behavior of pepper function "Returns a failure exit code if not all minions respond".

What I really want is that to make saltstack plugin abort when there has empty response with some minions, which I am believe is edge case.

And after I restart those minions, every things is working fine.

But it's really hard to say that empty response is an error definitely. So I will close this issue.

thanks.
