### ISSUE TITLE
  file.recurse Cannot execute concurrently If Jenkins executes multiple tasks at once, it will be wrong

### ISSUE THREAD

**Issue by jofia** [jenkinsci/saltstack-plugin#114]
# i use jenkins to execute salt jobs，The execution command is as follows，

 sudo salt ccic_main_dev state.sls file_cd_parallel 'pillar={"date_dir":{{date_dir}}}' concurrent=True queue=True
date_dir Is a variable that is automatically generated when the task is executed

**# The file_cd_parallel.sls is as follows:**

{% set app_flag = 'env' %}
{% set env_params = salt['analyzeUrl.getData'](pillar['configCenter'],pillar['profile'],app_flag,'main') %}
{% set app_root = pillar['app_root'] %}
{% set username = pillar['username'] %}
{% set url = app_root + '/' + 'parallel' + '/' + pillar['date_dir'] %}
{% set branch_name = env_params.branch_name %}
create_deploy_dir_if_need:
  cmd.run:
    - name: mkdir -p {{ app_root }}/parallel/{{pillar['date_dir']}}
    - unless: test -d {{ app_root }}/parallel/{{pillar['date_dir']}}
    - runas: {{ username }}
copy_to_deploy_dir:
  file.recurse:
    - name: {{ app_root }}/parallel/{{pillar['date_dir']}}
    - source: salt://files/packages/{{ branch_name }}/{{pillar['date_dir']}}
    - user: {{ username }}
    - group: {{ pillar['group'] if pillar['group'] is defined else pillar['username'] }}
    - dir_mode: 755
    - require:
      - cmd: create_deploy_dir_if_need

# If Jenkins executes multiple tasks at once, it will be wrong
FailedConsole Output

Started by upstream project "platform/nightly-37/studio-ui-nightly" build number 109
originally caused by:
 Started by user Jack Sun
[EnvInject] - Loading node environment variables.
Building remotely on cm-build153 (slave-linux) in workspace /home/jenkins/workspace/salt-env-deploy/ccic-deploy
Running jid: 20171124112043628888
Waiting for 1 minions
1 minions are done
ERROR: One or more minion did not return code 0

Response on state.sls file_cd_parallel 'pillar={"date_dir":2017-11-24_11-22-02_studio-ui-nightly}' concurrent=True queue=True for ccic_main_dev37:
[{"ccic_main_dev37": {
  "return":   {
    "file_|-copy_to_deploy_dir_|-/usr/local/ccic_main_dev/parallel/2017-11-24_11-22-02_studio-ui-nightly_|-recurse":     {
      "comment": "Recurse failed: none of the specified sources were found",
      "_stamp": "2017-11-24T03:20:46.013144",
      "pchanges": {},
      "return": "Error: file.recurse",
      "retcode": 2,
      "success": false,
      "start_time": "11:20:45.328593",
      "jid": "20171124112043628888",
      "name": "/usr/local/ccic_main_dev/parallel/2017-11-24_11-22-02_studio-ui-nightly",
      "fun": "state.sls",
      "result": false,
      "duration": 683.444,
      "__run_num__": 1,
      "changes": {},
      "id": "ccic_main_dev37",
      "__id__": "copy_to_deploy_dir"
    },
    "cmd_|-create_deploy_dir_if_need_|-mkdir -p /usr/local/ccic_main_dev/parallel/2017-11-24_11-22-02_studio-ui-nightly_|-run":     {
      "comment": "Command \"mkdir -p /usr/local/ccic_main_dev/parallel/2017-11-24_11-22-02_studio-ui-nightly\" run",
      "name": "mkdir -p /usr/local/ccic_main_dev/parallel/2017-11-24_11-22-02_studio-ui-nightly",
      "start_time": "11:20:44.733249",
      "result": true,
      "duration": 586.781,
      "__run_num__": 0,
      "changes":       {
        "pid": 22415,
        "retcode": 0,
        "stderr": "",
        "stdout": ""
      },
      "__id__": "create_deploy_dir_if_need"
    }
  },
  "out": "highstate"
}}]
ERROR: Build step failed with exception
java.lang.RuntimeException: Salt failure detected
	at com.waytta.SaltAPIBuilder.perform(SaltAPIBuilder.java:310)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:496)
	at hudson.model.Run.execute(Run.java:1739)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:419)
Build step 'Send a message to Salt API' marked build as failure
Finished: FAILURE

**Comment by jofia** [comment]
Please help to solve this problem，thanks

**Comment by mchugh19** [comment]
Thanks for the report. To make sure I understand your issue, it seems like you have a state that creates a directory structure, then pushes out files to that directory. Then the problem seems to be that salt ran the file.recurse before your cmd.run which created the directory structure. Is this correct?

If that is the case, then the issue is the ordering of your states. On the file.recurse you could add a 
```
requires: 
  - cmd: create_deploy_dir_if_need
```
to ensure that the directory structure is already in place.

The error on your state mentions "Recurse failed: none of the specified sources were found" so it might also be possible that the source for file.recurse isn't correct. 

Either way, it appears that salt is successfully being activated by jenkins. You might want to send this query to the salt mailing list https://groups.google.com/forum/#!forum/salt-users

**Comment by jofia** [comment]
The salt output log is out of order. You can look at start time. After the folder has been created, the file.recurse operation is executed。File.recurse is unstable. If you call state module in parallel with Jenkins, the failure rate is one percent. I would like to ask if file.recurse does not support parallel execution

[{"ccic_main_dev37": {
"return": {
"file_|-copy_to_deploy_dir_|-/usr/local/ccic_main_dev/parallel/2017-11-24_11-22-02_studio-ui-nightly_|-recurse": {
"comment": "Recurse failed: none of the specified sources were found",
"stamp": "2017-11-24T03:20:46.013144",
"pchanges": {},
"return": "Error: file.recurse",
"retcode": 2,
"success": false,
# "start_time": "11:20:45.328593",
"jid": "20171124112043628888",
"name": "/usr/local/ccic_main_dev/parallel/2017-11-24_11-22-02_studio-ui-nightly",
"fun": "state.sls",
"result": false,
"duration": 683.444,
"run_num": 1,
"changes": {},
"id": "ccic_main_dev37",
"id": "copy_to_deploy_dir"
},
"cmd|-create_deploy_dir_if_need_|-mkdir -p /usr/local/ccic_main_dev/parallel/2017-11-24_11-22-02_studio-ui-nightly_|-run": {
"comment": "Command "mkdir -p /usr/local/ccic_main_dev/parallel/2017-11-24_11-22-02_studio-ui-nightly" run",
"name": "mkdir -p /usr/local/ccic_main_dev/parallel/2017-11-24_11-22-02_studio-ui-nightly",
# "start_time": "11:20:44.733249",
"result": true,
"duration": 586.781,
"run_num": 0,
"changes": {
"pid": 22415,
"retcode": 0,
"stderr": "",
"stdout": ""
},
"id": "create_deploy_dir_if_need"
}

**Comment by jofia** [comment]
I'm sorry my English isn't very good

**Comment by mchugh19** [comment]
Ah ha! I'm afraid I don't know about the file.recurse option with parallelism. I suggest you post an[ issue on the saltstack git](https://github.com/saltstack/salt/issues), or ask in the [salt-users group](https://groups.google.com/forum/#!forum/salt-users).

**Comment by jofia** [comment]
thanks i have post an issue on the saltstack git,thanks very much
https://github.com/saltstack/salt/issues/44672
