### ISSUE TITLE
Question Regarding Failures

### ISSUE THREAD

**Issue by twllight** [jenkinsci/saltstack-plugin#118]
I've just started using this plugin to help build our CI/CD pipeline for salt, and it's really great thank you for taking the time to set it up!

In my case, i'm running a highstate on an ephemeral docker container with a docker container as the master as well, and after a highstate is applied, I'd like to run a suite of tests on the system which has been "built" by the highstate. 

However, if there is a failure within applying the salt code, say a broken state, I'd like to let the build continue, and allow my tests to then run, which would catch that error and fail on the failed test. Is there a way to override the salt plugin in such a way to have it ignore errors?

Thanks

**Comment by mchugh19** [comment]
Hey hey hey,

You should be able to uncheck the "wait for completion" check box on the
local type. This should send off the command to your saltmaster, but not
wait for the results and thus shouldn't have anything to validate.

If you instead need to know when the salt run is complete but still not
validate the results, then that is not currently supported, but can be.

**Comment by twllight** [comment]
Hello!

Thanks for the quick response! I would still like to know when the run complets, so that I can fire off my test suite knowing that i'm not failing tests because of waiting for a highstate to complete.
