### ISSUE TITLE
Feature: Support for credentials storage

### ISSUE THREAD

**Issue by zerthimon** [jenkinsci/saltstack-plugin#13]
It'd be amazing if this plugin would use jenkins creds storage, so a user would then just need to specify the cred, not the username/password in every salt step in every job.

**Comment by mchugh19** [comment]
Boom! https://github.com/jenkinsci/saltstack-plugin/releases/tag/1.7.0-beta

Can you please try this out and see if it works as expected? I happened to have recently worked up that capability, but have not yet cut a release. While it works for me, it would be nice to get slightly wider testing.

**Comment by zerthimon** [comment]
Wow, cool! I'll test that tomorrow!

**Comment by zerthimon** [comment]
I tested it and ..... well ..... It works great!

**Comment by mchugh19** [comment]
Changes released in 1.7.0
