### ISSUE TITLE
tgt_type parameter is missing when pipeline mode is using

### ISSUE THREAD

**Issue by sotona-** [jenkinsci/saltstack-plugin#130]
Hello.
Jenkins: 2.138.3
Salt-plugin: 3.2.0
When I'm configuring salt-API call in a pipeline with any target type istead of 'glob', 'tgt_type' parameter is missing in request. And salt master tries to find target as 'glob' ans returns 'no minions matched'
For example:
````java
pipeline fragment:
saltresult = salt authtype: 'ldap', clientInterface: local(blockbuild: true,
                function: 'test.ping', jobPollTime: 16, target: 'I@group:cpc', targetType: 'compound'),
                credentialsId:  salt_cred_id, servername: salt_url
            //def prettyJson = JsonOutput.prettyPrint(saltresult)
            println(saltresult)
````
Captured json from request:
```json
{"client":"local_async","tgt":"I@group:cpc","fun":"test.ping"}
```

But 'tgt_type'  exixts in request json in freestyle project mode with all same parameters.

**Comment by sotona-** [comment]
I'm sorry, problen was with symbol's register.
All working with  'targettype' instead of  'targetType'.

**Comment by mchugh19** [comment]
Excellent! Sorry for the delay, I was away on a work trip. Glad it got worked out!
