### ISSUE TITLE
Feature Request - Slave Configuration from Salt

### ISSUE THREAD

**Issue by damon-atkins** [jenkinsci/saltstack-plugin#137]
Hi Guys,
   There are plugins like https://plugins.jenkins.io/slave-setup  However it would be nice to have salt  configure Jenkins slaves, without a restart of Jenkins.    Use salt to build Jenkins slave, once built information is reported back to the salt-master, which then configures Jenkins with the slave information so the new slaves are accepted.

Unless you have another way to do this?

**Comment by mchugh19** [comment]
I agree that would be a useful feature, but I think it's out of scope for this plugin. It would be best as its own dedicated plugin.
