### ISSUE TITLE
JSon Response with different format

### ISSUE THREAD

**Issue by chforster** [jenkinsci/saltstack-plugin#139]
Sometimes I receive a different JSon Response Format for the same Request.

I use Salt-Stack Plugin 3.2.1, Salt 2019.2.0 and Tornado 4.2.1.

The Jenkins Command is:

    salt authtype: 'pam', clientInterface: local(arguments: "'/scripts/tomcat.sh stop'", function: "cmd.run", blockbuild: true, jobPollTime: 15, minionTimeout: 30, target: "opsrole:app-srv-*", targettype: "grain"), credentialsId: 'saltmaster', servername: "https://my.saltmaster.com", skipValidation: "true"

The Request within the Salt Logs (Jenkins) is:

    Sending JSON: {"client":"local_async","full_return":true,"tgt":"opsrole:app-srv-*","tgt_type":"grain","fun":"cmd.run","arg":"/scripts/tomcat.sh stop"}

The VALID Response, which I reserve most of the time (approx 9 out of 10 times) is:

    [
        {
            "srv1.test.com":{
                "return":"Stopping Tomcat...\nWaiting for Tomcat to exit...\nStopped Tomcat."
                ,"retcode":0,"success":true},
            "srv2.test.com":{
                "return":"Stopping Tomcat...\nWaiting for Tomcat to exit...\nStopped Tomcat."
                ,"retcode":0,"success":true},
            "srv3.test.com":{
                "return":"Stopping Tomcat...\nWaiting for Tomcat to exit...\nStopped Tomcat."
                "retcode":0,"success":true},
            "srv4.test.com":{
                "return":"Stopping Tomcat...\nWaiting for Tomcat to exit...\nStopped Tomcat."
                "retcode":0,"success":true}
        }
    ]

The INVALID Response I receive is

    [
        [
            {
                "Function":"cmd.run",
                "jid":"20190820121646732783",
                "Result":{
                    "srv1.test.com":{
                        "return":"Stopping Tomcat...\nWaiting for Tomcat to exit...\nStopped Tomcat."
                        ,"retcode":0,"success":true},
                    "srv2.test.com":{
                        "return":"Stopping Tomcat...\nWaiting for Tomcat to exit...\nStopped Tomcat."
                        ,"retcode":0,"success":true},
                    "srv3.test.com":{
                        "return":"Stopping Tomcat...\nWaiting for Tomcat to exit...\nStopped Tomcat."
                        "retcode":0,"success":true},
                    "srv4.test.com":{
                        "return":"Stopping Tomcat...\nWaiting for Tomcat to exit...\nWaiting for Tomcat to exit...\nWaiting for Tomcat to exit...\nWaiting for Tomcat to exit...\nWaiting for Tomcat to exit...\nWaiting for Tomcat to exit...\nWaiting for Tomcat to exit...\nWaiting for Tomcat to exit...\nStopped Tomcat.",
                        "retcode":0,"success":true}
                },
                "Target":"opsrole:app-srv-*",
                "Target-type":"grain",
                "User":"jenkins",
                "StartTime":"2019, Aug 20 12:16:46.732783",
                "Minions":[
                    "srv1.test.com","srv2.test.com","srv3.test.com","srv4.test.com"
                ],
                "Arguments":["/scripts/tomcat.sh stop"]
            }
        ]
    ]

I have tried to reproduce the Output but it occurs randomly.

Why do I receive this different Output sometimes?
The Problem is, that I can not rely on such a different output format.

Regards,
Christoph

**Comment by mchugh19** [comment]
That's interesting! The jenkins plugin just forwards the response it receives from the saltapi. If that output changes, it might be something to do with the saltapi. I suggest opening an issue on https://github.com/saltstack/salt/issues to investigate further.
