### ISSUE TITLE
Plugin not allowing selection of credentials during creation

### ISSUE THREAD

**Issue by tyhunt99** [jenkinsci/saltstack-plugin#16]
I am trying to create a new project in jenkins. It will simply call highstate. The build step is configured to use a user with ssh key set up via jenkins credentials. However in the credential selector box I only ever get none.
![capture](https://cloud.githubusercontent.com/assets/12551470/13762645/eb813ebe-ea05-11e5-8f18-54d54c9f6288.JPG)
 It says 'cannot find any credentials with id'. I have verified the credentials are set up properly and it does work with the git plugin.

**Comment by mchugh19** [comment]
Uh oh. But thanks for the feedback

In the credentials selector, have you clicked the add button and added the username/password info for your jenkins instance? After doing so, you should be able to select those credentials in the dropdown which in your screenshot displays none.

**Comment by tyhunt99** [comment]
Yea I tried clicking the add button and it does add it to the credentials (as in I go to credentials under the jenkins menu and it is listed) but still doesn't show up in the selector box.

**Comment by mchugh19** [comment]
Well, that's not working as intended. Sorry about that. 

I am not able to replicate, but will look into it.

**Comment by tyhunt99** [comment]
Thanks! Let me know if you need anymore information

**Comment by mchugh19** [comment]
@tyhunt99 So in your install, even though you've added credentials, only the "- none -" option is displayed in the dropdown? 

If that is the case, might you be testing with a jenkins account that has limited permissions? There isn't much going on to display credentials, just showing all saved username/password creds.
https://github.com/jenkinsci/saltstack-plugin/blob/master/src/main/java/com/waytta/SaltAPIBuilder.java#L512

**Comment by tyhunt99** [comment]
Yes I have added credentials both to the global jenkins and under my user. I also looked at our current security settings and it is set to allow anyone to do anything so permissions shouldn't be causing issues. 

I used the add credentials inside the build step and it properly added them; they showed up correctly in the jenkins credential manager and I was also able to select them in the git scm plugin.

**Comment by mchugh19** [comment]
Are you seeing any errors or possibly helpful info in the jenkins logs? I'm still not able to replicate this behavior and I've tried a few different environments.

**Comment by tyhunt99** [comment]
It would appear that if I use the simple username password credential its works. I have been trying to use SSH username with private key and those do not show up. Are they supported?

**Comment by mchugh19** [comment]
Ah! There's the problem! The saltapi requires a username and a password. So only simple username credentials are supported.

**Comment by tyhunt99** [comment]
Thanks for your help! It may be useful to make a note on in the docs that it only supports the simple password username combo
