### ISSUE TITLE
Minion count is off by 1

### ISSUE THREAD

**Issue by zerthimon** [jenkinsci/saltstack-plugin#20]
A job targeted just one minion....
```
15:08:31 Running jid: 20160411150831551700
15:08:32 Waiting for 1 minions
15:08:32 2 minions are done
15:08:32 ERROR occurred !
```

**Comment by mchugh19** [comment]
Interesting. How were you targeting the minion?

In sending the following json, it works as expected:
```json
[DEBUG] Sending JSON: [{"client":"local","tgt":"web1","expr_form":"glob","fun":"cmd.run","arg":["false 1"]}]
```

```
Running jid: 20160411155706886441
Waiting for 1 minions
1 minions are done
[DEBUG] Received response: [{"web1":""}]
Response on cmd.run false 1 for web1:
[{"web1": ""}]
Finished: SUCCESS
```

**Comment by zerthimon** [comment]
I used targeting 'by grain' with expression 'roles:myrole' a server's grains have:
```
salt-call grains.append roles myrole
```

There's only one server with this role.

**Comment by mchugh19** [comment]
@zerthimon Interesting. Are you able to replicate? Does targeting in that way always result in targeting one minion, but two respond? 

As a quick sanity check, you may also want to ensure that you don't have an old salt-minion process lying around.

**Comment by mchugh19** [comment]
I am still not able to replicate the multiple minion return problem. I've even tried starting multiple minion processes on a test machine, but still don't have this issue. Are you still seeing this behavior?

**Comment by zerthimon** [comment]
I'll try to reproduce this again and post more info.
I think it's the logging problem, not the functional one.

**Comment by zerthimon** [comment]
Yep, I'm able to reproduce... but's a very "synthetic" scenario.
```
Started by user zerthimon
[EnvInject] - Loading node environment variables.
Building in workspace /var/lib/jenkins/jobs/test/workspace
Running jid: 20160418205847821057
Waiting for 1 minions
2 minions are done
ERROR occurred !
ERROR: One or more minion did not return code 0 for state.sls asdfasdf for roles:common:
[{
  "outputter": "highstate",
  "data": {"common": ["No matching sls found for 'asdfasdf' in env 'base'"]}
}]
Build step 'Send a message to Salt API' marked build as failure
Notifying upstream projects of job completion
Finished: FAILURE

```
This appears to get triggered on salt's error (in my case a nonexistant sls)
Here is the config:
```
Client Interface: local
Wait for completion: Checked
Target: roles:common
Target Type: grain
Function: state.sls
Arguments: asdfasdf
KWArguments: queue=True
Save output to environment variable: Not Checked
```

**Comment by mchugh19** [comment]
I wonder if there is something else going on with the grain matcher, as I an unable to replicate. 

I just tried duplicating using the `host:web1` grain (unique as it refers to the hostname of the minion)
```
Started by user anonymous
Building in workspace /home/xian/work/saltstack-plugin/work/jobs/salt/workspace
Running jid: 20160506143115395090
Waiting for 1 minions
1 minions are done
ERROR occurred !
ERROR: One or more minion did not return code 0 for state.sls lksdkl for host:web1:
[{"web1": ["No matching sls found for 'lksdkl' in env 'base'"]}]
Build step 'Send a message to Salt API' marked build as failure
Finished: FAILURE
```

Have you reviewed the grains on that host to ensure there isn't somehow a mix-up, or that the host is possibly running duplicate salt-minion processes? 

If you are able, you can try out [this release](https://github.com/jenkinsci/saltstack-plugin/releases/tag/1.7.1-beta2) to print out the return from the salt-api to see why jenkins thinks you are getting back results from multiple minions.

**Comment by mchugh19** [comment]
Closing out as I'm unable to replicate. If this comes up again, feel free to reopen.
