### ISSUE TITLE
When targeting results in zero minions the plugin doesn't report any error

### ISSUE THREAD

**Issue by zerthimon** [jenkinsci/saltstack-plugin#25]
If there are no minions that could be targeted, the plugin returns with:
```
16:16:37 Response on test.ping  for zinfra*:
16:16:37 [{}]
```
And continues the run....

Salt detects this well:
```
root@infra01:/# salt zinfra\* test.ping
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
root@infra01:/# echo $?
2
root@infra01:/#
```

Is this another salt-api limitation ?

**Comment by mchugh19** [comment]
That should only occur when you have a local job and don't have checked
"Wait for completion". In the unchecked case it simply sends off the
request and does not verify the job.

If you would like to ensure that your process ran, check that box
(local_batch will also fail as expected). At this point you should see the
job error out as it could not get a job ID.

I've just verified this is true, but if you have any problems or questions
please let me know.

Thanks!

**Comment by zerthimon** [comment]
Yeah, thanks! 
"Wait for completion" works for me.
Closing
