### ISSUE TITLE
Please enable parameterized 'Pillar value'

### ISSUE THREAD

**Issue by rbjorklin** [jenkinsci/saltstack-plugin#31]
I need to be able to use parameters in the 'Pillar value' field. For example let's say I have two parameters:
APPLICATION
VERSION

I would like to be able to do this:
Pillar value: `{"application": "${APPLICATION}", "version": "${VERSION}"}`

**Comment by rbjorklin** [comment]
On a closer look it looks like it [should already be there](https://github.com/jenkinsci/saltstack-plugin/blob/master/src/main/java/com/waytta/SaltAPIBuilder.java#L434-L436) is there any example of how to use it? The way I'm trying it above is not working.

**Comment by rbjorklin** [comment]
Even further investigation shows that the correct way to parameterize is by using `{{PARAMETER}}` maybe this should be mentioned somewhere since Jenkins default seems to be `$PARAMETER`.
The comment [on line 109-110](https://github.com/jenkinsci/saltstack-plugin/blob/master/src/main/java/com/waytta/Utils.java#L109-L123) indicates that correct way is `$PARAMETER` however the code says different.

**Comment by mchugh19** [comment]
You are correct. The jenkins "?" help screens should describe the syntax. The reason for not using the $VARIABLE syntax was that it matches shell variables and you might want to use salt to interface with them minion side. For example `salt 'hostname' cmd.run 'echo $PATH'` would evaluate $PATH on the minion, while `echo {{PATH}}` would evaluate a jenkins variable.
