### ISSUE TITLE
Call hook api

### ISSUE THREAD

**Issue by dkiser** [jenkinsci/saltstack-plugin#34]
As a salt api plugin user I should be able to call and arbitrary hook Uri with arbitrary key/values So that I can take advantage of hooks and reactor states in salt.
- Key/value pairs should be JSON posts to the hook URI
- Invocation should provide a configurable auth token parameter, if not defined login dance should happen. If login dance happens...token is optionally provided back to caller
- Should be able to configure "eauth" parameter as global or invocation parameter

**Comment by mchugh19** [comment]
Calling the cherrypy [/hook interface](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#salt.netapi.rest_cherrypy.app.Webhook.POST) was just added to master and will be in the 2.0 release.

Support for specifying an auth token and changing the eauth parameter globally, were not added. Feel free to open a new request as needed.

**Comment by mchugh19** [comment]
Released 2.0
