### ISSUE TITLE
Plugin reports failure early but job continues

### ISSUE THREAD

**Issue by rbjorklin** [jenkinsci/saltstack-plugin#39]
I started a job that takes quite some time to return (1,5h) however it returned after just a few minutes with the following:

```
Started by user John Doe
Building in workspace /var/lib/jenkins/workspace/Upgrade application
Problem with state.orchestrate  for not_used:
net.sf.json.JSONException: JSONObject["return"] is not a JSONArray.

{"Error": "java.io.IOException: Server returned HTTP response code: 500 for URL: https://salt-master.example.com:8000
Build step 'Send a message to Salt API' marked build as failure
Finished: FAILURE
```

**Comment by mchugh19** [comment]
Looks like it wasn't able to reach the given URL. But the job was kicked off? Strange!

Are you able to replicate and repeat?

**Comment by rbjorklin** [comment]
I'll try to replicate, any kind of logging I should enable beforehand?

**Comment by mchugh19** [comment]
You can follow the steps in https://wiki.jenkins-ci.org/display/JENKINS/saltstack-plugin#Logging%20Configuration to see what is being sent to the saltapi as well as the return. But from the looks of things, this is an issue with the salt-api. Jenkins is getting back http error 500.

Googling that turned up https://github.com/saltstack/salt/issues/23408. So you might want to post there with any updates.

**Comment by rbjorklin** [comment]
Looking at that saltstack issue it looks like my problem might be solved by setting a different timeout. Any way I can do that for the plugin? (Can't find the option)

**Comment by mchugh19** [comment]
Not yet. Adding timeout to the todo list.

**Comment by rbjorklin** [comment]
A closer look at the jenkins job showed that it times out after exactly 5 minutes (300 seconds) as mentioned [here](https://github.com/saltstack/salt/issues/23408#issuecomment-113556710). Just tried setting the `rest_timeout` on the server and will get back to you if when the job has been run again.

**Comment by mchugh19** [comment]
Also, if this is with clientInterface local, have you checked the "wait for completion" checkbox?

That will cause jenkins to send off the request, then poll the salt-master to query status. It would be good to know if it is failing in that first request send, or later in the status poll.

**Comment by mchugh19** [comment]
@rbjorklin Any updates. Did the rest_timeout or "wait for completion" help?

**Comment by rbjorklin** [comment]
Got it working with this in `/etc/salt/master`:

    rest_cherrypy:
      port: 8000
      expire_responses: False

    rest_timeout: 7200
