### ISSUE TITLE
Support https_proxy

### ISSUE THREAD

**Issue by bemeyert** [jenkinsci/saltstack-plugin#43]
Hi,

I just tried to use the plugin and according to tcpdump and the access.log of the proxy in front of the API it doesn't even connect to the API server. Not even the "Test connection" works. 
servername: https://saltapi.office.blah.de:443

A Curl in a Shell buildstep in the same job works just fine:
```
[...]
[salt_api] $ /bin/sh -xe /tmp/hudson310140799158824452.sh
+ curl -kI https://saltapi.office.blah.de:443
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   181    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 10 Nov 2016 09:00:29 GMT
Content-Type: application/json
Content-Length: 181
Connection: keep-alive
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Set-Cookie: session_id=6d2f14935544aa64d0cbe4e80230d26d4697ae8e; expires=Thu, 10 Nov 2016 19:00:29 GMT; Path=/
[...]
```
I can't give you any Jenkins logs since I don't know what the right logger would be. The only error I get in the Console Output is the followig:
```
Auth Error: net.sf.json.JSONException: JSONObject["return"] is not a JSONArray.

{"Error": "java.net.SocketTimeoutException: connect timed out
Build step 'Send a message to Salt API' marked build as failure
Finished: FAILURE
```
I made sure that our self-signed cert is in Javas keystore.

Jenkins Version: 2.19.2
Salt Plugin Version: 1.7.1

Any help would be much appreciated.

**Comment by bemeyert** [comment]
Oh, I RTFM'd and added a logger for `com.waytta.saltstack`. But this one shows nothing too.

**Comment by mchugh19** [comment]
It sounds like the response back isn't the expected JSON. Are you using the cherrypy api? 

```
# curl -k http://localhost:8000
{"clients": ["_is_master_running", "local", "local_async", "local_batch", "local_subset", "runner", "runner_async", "ssh", "ssh_async", "wheel", "wheel_async"], "return": "Welcome"}

# curl -kI http://localhost:8000
HTTP/1.1 200 OK
Content-Length: 181
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/3.5.0
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Fri, 11 Nov 2016 16:47:27 GMT
Access-Control-Allow-Origin: *
Content-Type: application/json
Set-Cookie: session_id=35656f11bd7924f85912d406c8b1a0536a7fa6ab; expires=Sat, 12 Nov 2016 02:47:27 GMT; Path=/
```

**Comment by mchugh19** [comment]
You should be able to login with a simple JSON string and get back a response. The connect timeout makes it sounds as if the jenkins host isn't able to reach the salt-master's url. 

```
# curl -ik http://localhost:8000/login -H 'Content-Type: application/json' -d '[{"eauth":"pam","password":"jenkins","username":"jenkins"}]'
HTTP/1.1 200 OK
Content-Length: 187
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/3.5.0
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Fri, 11 Nov 2016 16:49:55 GMT
Access-Control-Allow-Origin: *
X-Auth-Token: 4c9f373b331b39417b20d7eecbd6b5f15439d15e
Content-Type: application/json
Set-Cookie: session_id=4c9f373b331b39417b20d7eecbd6b5f15439d15e; expires=Sat, 12 Nov 2016 02:49:55 GMT; Path=/

{"return": [{"perms": [".*", "@runner"], "start": 1478882995.909112, "token": "4c9f373b331b39417b20d7eecbd6b5f15439d15e", "expire": 1478926195.909112, "user": "jenkins", "eauth": "pam"}]}
```

**Comment by bemeyert** [comment]
I am using the Cherypy-API. An when authenticating from the command line as Jenkins-User it works as expected:
```
jenkins@jenkins$ curl -ik --noproxy saltapi https://saltapi:443/login -H 'Content-Type: application/json' -d '[{"eauth":"pam","password":"jenkins","username":"jenkins"}]'
HTTP/1.1 200 OK
Server: nginx
Date: Mon, 14 Nov 2016 09:46:50 GMT
Content-Type: application/json
Content-Length: 210
Connection: keep-alive
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
X-Auth-Token: 48105ca6efaf3c0d6faa6616097e7d8a0d6a359f
Set-Cookie: session_id=48105ca6efaf3c0d6faa6616097e7d8a0d6a359f; expires=Mon, 14 Nov 2016 19:46:50 GMT; Path=/

{"return": [{"perms": [".*", "@runner", "@wheel", "@jobs"], "start": 1479116810.4126899, "token": "48105ca6efaf3c0d6faa6616097e7d8a0d6a359f", "expire": 1479160010.4126911, "user": "jenkins", "eauth": "pam"}]}
```
We have the `https_proxy` environment variable set on the Jenkins server. But Jenkins ignores it as you can see by the first `curl` command I posted.

**Comment by mchugh19** [comment]
Oh I see. Then it's really a matter of supporting the https_proxy env var. Yes, that isn't currently supported. I'll look into it.

**Comment by bemeyert** [comment]
@mchugh19 I'm not sure if this is correct. The `curl` in the Shell build step didn't have the proxy variable, so your plugin shouldn't have it too. Meaning, the Jenkins process (slave.jar) doesn't have the variable set (I don't know why). Also the proxy should not been used! That's why I had to type `curl -ik --noproxy saltapi` on the command line. 
I'd still like to know, what really happens inside the plugin. As said above, according to `tcpdump` there is no connection whatsoever to the API host when I run a build with the plugin configured.

**Comment by mchugh19** [comment]
Understood. The tcpdump logging is certainly strange. 

[All the plugin does](https://github.com/jenkinsci/saltstack-plugin/blob/master/src/main/java/com/waytta/Utils.java#L97) is attempt to connect to the url and post the json, just like the curl above.

Since you are not seeing any connection from the tcpdump, it sounds like there is some other issue. Have you tried tcpdump from the Jenkins side to see that a connection is being attempted? 

Additionally, could you please test out the current master branch? I've just cut an [early beta hpi](https://github.com/jenkinsci/saltstack-plugin/releases/tag/v2.0-beta1) which incorporates a few cleanups and my hope is we could see more about the exception causing this connectivity issue.

**Comment by bemeyert** [comment]
I did the Tcpdump again. With `tcpdump -i bond0 -s 0 -l -w - dst port 443 and dst host saltapi` I listened for connections. I did a "Test Connection" in "Salt API" build step and that gave me no traffic at all an the following error:
```
Client error: Auth Error: net.sf.json.JSONException: JSONObject["return"] is not a JSONArray.
{"Error": "java.net.SocketTimeoutException: connect timed out
```
Also while listening to connections to our proxy (just to be on the safe side) I did a tcpdump which gave me "zip" again.

To make sure I'm didn't mess up the tcpdump I made a `curl --noproxy saltapi -I https://saltapi` from CLI which succedded and showed traffic.


Before trying your beta I will need to figure how to install the plugin. My Jenkins-foo is not very mighty ;) I get back to you A.S.A.P.

P.S.: Isn't there a way to get some sort of debugging output from the plugin to see what calls are made?

**Comment by bemeyert** [comment]
I installed the v2.0-beta1 tag and still the same. Nothing from the logger `com.waytta.saltstack`, nothing in the tcpdump and the same error as above.

**Comment by mchugh19** [comment]
So if tcpdump isn't seeing any traffic being sent from the jenkins server, and the error you are getting back from the plugin states connection timed out, it sure sounds like there is a local configuration problem. 

The plugin code will log the json being sent to the salt master as well as the response, but there is no logging code path before the login, as that is the first thing it does. The connect timed out error seems to be pretty valid -- if it isn't sending traffic, the connection will time out. My hope from the 2.0beta1 release is that you might have gotten a different error from the http connection which might have helped. 

Could you try running jenkins on another VM? There really isn't any magic at this point. It seems there is something funky about the jenkins environment that is limiting network communication. I'm really stretching here but possibly selinux, or funky iptables rules?

**Comment by bemeyert** [comment]
It would help me a lot to see the actual HTTP request. 
I can't move Jenkins somewhere else. And to get an exhaustive (containing all traffic) network dump for analysis in Wireshark, I would have to tell too many people to stop working ;)

**Comment by mchugh19** [comment]
You can get the output of the http connections by creating a new `sun.net.www.protocol.http.HttpURLConnection` logger set to FINEST. I wasn't able to get this to show any output until also setting a blank default Jenkins logger on /jenkins/log/levels also to FINEST.

**Comment by mchugh19** [comment]
So you can compare, this is the output from running a subset job

```
Nov 18, 2016 10:04:16 PM FINEST sun.net.www.protocol.http.HttpURLConnection
ProxySelector Request for http://localhost:8000/login
Nov 18, 2016 10:04:16 PM FINEST sun.net.www.protocol.http.HttpURLConnection
Proxy used: DIRECT
Nov 18, 2016 10:04:16 PM FINE sun.net.www.protocol.http.HttpURLConnection
sun.net.www.MessageHeader@6d8aae179 pairs: {POST /login HTTP/1.1: null}{Accept: application/json}{Content-Type: application/json}{Cache-Control: no-cache}{Pragma: no-cache}{User-Agent: Java/1.8.0_101}{Host: localhost:8000}{Connection: keep-alive}{Content-Length: 59}
Nov 18, 2016 10:04:16 PM FINEST sun.net.www.protocol.http.HttpURLConnection
KeepAlive stream used: http://localhost:8000/login
Nov 18, 2016 10:04:16 PM FINE sun.net.www.protocol.http.HttpURLConnection
sun.net.www.MessageHeader@73068da912 pairs: {null: HTTP/1.1 200 OK}{Content-Length: 187}{Access-Control-Expose-Headers: GET, POST}{Vary: Accept-Encoding}{Server: CherryPy/3.5.0}{Allow: GET, HEAD, POST}{Access-Control-Allow-Credentials: true}{Date: Fri, 18 Nov 2016 22:04:16 GMT}{Access-Control-Allow-Origin: *}{X-Auth-Token: 40a68965320d6e4ce95af7adae0a443474cbfd99}{Content-Type: application/json}{Set-Cookie: session_id=40a68965320d6e4ce95af7adae0a443474cbfd99; expires=Sat, 19 Nov 2016 08:04:16 GMT; Path=/}
Nov 18, 2016 10:04:16 PM FINEST sun.net.www.protocol.http.HttpURLConnection
ProxySelector Request for http://localhost:8000/
Nov 18, 2016 10:04:16 PM FINEST sun.net.www.protocol.http.HttpURLConnection
KeepAlive stream retrieved from the cache, sun.net.www.http.HttpClient(http://localhost:8000/login)
Nov 18, 2016 10:04:16 PM FINEST sun.net.www.protocol.http.HttpURLConnection
Proxy used: DIRECT
Nov 18, 2016 10:04:16 PM FINE sun.net.www.protocol.http.HttpURLConnection
sun.net.www.MessageHeader@1568d30c10 pairs: {POST / HTTP/1.1: null}{Accept: application/json}{Content-Type: application/json}{X-Auth-Token: 40a68965320d6e4ce95af7adae0a443474cbfd99}{Cache-Control: no-cache}{Pragma: no-cache}{User-Agent: Java/1.8.0_101}{Host: localhost:8000}{Connection: keep-alive}{Content-Length: 125}
Nov 18, 2016 10:04:31 PM FINEST sun.net.www.protocol.http.HttpURLConnection
KeepAlive stream used: http://localhost:8000
Nov 18, 2016 10:04:31 PM FINE sun.net.www.protocol.http.HttpURLConnection
sun.net.www.MessageHeader@2221514712 pairs: {null: HTTP/1.1 200 OK}{Content-Length: 373}{Access-Control-Expose-Headers: GET, POST}{Cache-Control: private}{Vary: Accept-Encoding}{Server: CherryPy/3.5.0}{Allow: GET, HEAD, POST}{Access-Control-Allow-Credentials: true}{Date: Fri, 18 Nov 2016 22:04:16 GMT}{Access-Control-Allow-Origin: *}{Content-Type: application/json}{Set-Cookie: session_id=40a68965320d6e4ce95af7adae0a443474cbfd99; expires=Sat, 19 Nov 2016 08:04:16 GMT; Path=/}
```

**Comment by bemeyert** [comment]
Hmm, I have configured the loggers as described. But still there only this:
```
Nov 21, 2016 9:21:42 AM FINEST sun.net.www.protocol.http.HttpURLConnection
ProxySelector Request for https://saltapi:443/login
Nov 21, 2016 9:21:42 AM FINEST sun.net.www.protocol.http.HttpURLConnection
Looking for HttpClient for URL https://saltapi:443/login and proxy value of DIRECT
Nov 21, 2016 9:21:42 AM FINEST sun.net.www.protocol.http.HttpURLConnection
Creating new HttpsClient with url:https://saltapi:443/login and proxy:DIRECT with connect timeout:5000
``` 
The access.logs of the API's proxy show nothing too.  Also I did a tcpdump again and the only traffic to the `saltapi` host was the connection between Minion and Master (the API is also the master).
Just to be sure:
1. I Created a new logger which named "salt" containing `sun.net.www.protocol.http.HttpURLConnection` with level set to FINEST.
2. Under `/log/levels` I changed the default logger (the empy one) to FINEST.

Any ideas left? 

cheers

**Comment by mchugh19** [comment]
That looks accurate. 
You can see from the example I posted earlier that the first connection was to "http://localhost:8000/login". After that succeeds, it then does a post "{POST /login HTTP/1.1: null}{Accept: ..."

In your example, jenkins attempts to reach "https://saltapi:443/login" and it never completes. This matches the original error returned: "Error": "java.net.SocketTimeoutException: connect timed out. 

It appears there is something preventing the jenkins host from resolving or otherwise getting out to the saltapi host.

**Comment by bemeyert** [comment]
HaHa, the whole time I was looking on the wrong host. I Pinned the job to a specific slave via the "Node and label parameter" plugin. So I concentrated on this slave. But the whole time the salt plugin was running on the Jenkins master. After figuring out what was happening I opened the port to the Salt-API in our firewall and everything worked as expected.

Thanks a lot for your time and patience
