### ISSUE TITLE
Only Global credentials are shown

### ISSUE THREAD

**Issue by bemeyert** [jenkinsci/saltstack-plugin#44]
In the Credentials drop-down I can only see those credentials which are on the global level. None of credentials for the folder are shown. To be sure I checked if I can see the folder credentials in the SCM part. I was able to select folder creds in the Git configuration.

Jenkins Version: 2.19.2
Salt Plugin Version: 1.7.1

Cheers

**Comment by mchugh19** [comment]
Not sure of the specifics, but I think this requires supporting the newer credentials 2.1.0 API. I've not seen any good documentation for supporting this yet. I'll continue to look into it, but pull requests welcome!

**Comment by bemeyert** [comment]
I see. Sadly I can't help you with any code. Cheers

**Comment by mchugh19** [comment]
This was just commited to master and will be in the next release

**Comment by mchugh19** [comment]
Released 2.0
