### ISSUE TITLE
rest_tornado support

### ISSUE THREAD

**Issue by fracklen** [jenkinsci/saltstack-plugin#45]
Just installed the v2.0-beta1.

It works like a charm when you run `rest_cherrypy`. However, when running `rest_tornado`, the login request is denied with 
```
HTTP/1.1 400 Bad Request
Date: Fri, 18 Nov 2016 20:07:02 GMT
Content-Length: 73
Content-Type: text/html; charset=UTF-8
Server: TornadoServer/4.2.1

<html><title>400: Bad Request</title><body>400: Bad Request</body></html>
```

This might be a bug in rest_tornado - I'm not that sure about the api spec.

The `rest_cherrypy` webserver accepts the login credentials in the form 
```json
[
  {
    "username": "rootus_rootus",
    "password": "thebigsecret",
    "eauth": "auto"
  }
]
```
 as well as 
```json
{
  "username": "rootus_rootus",
  "password": "thebigsecret",
  "eauth": "auto"
}
```

`rest_tornado` only accepts the latter

Btw - great kudos for the awesome plugin!

**Comment by fracklen** [comment]
I've filed an issue in saltstack/salt to get clarity of what is expected behaviour

**Comment by mchugh19** [comment]
Tornado support was just added via #70 

Supporting tornado caused some changes in the salt return
```json
Cherrypy:
"return": [{
  "master": "total 20\ndrwx------ 3 root root 4096 Mar 25 07:51 .\ndrwxr-xr-x 25 root root 4096 Mar 30 06:40 ..\n-rw-r--r-- 1 root root 3106 Oct 22 2015 .bashrc\n-rw-r--r-- 1 root root 148 Aug 17 2015 .profile\ndrwx------ 2 root root 4096 Mar 25 07:51 .ssh"
}]
```

```json
Tornado:
"Result": {
  "master": {
    "return": "total 20\ndrwx------ 3 root root 4096 Mar 25 07:51 .\ndrwxr-xr-x 25 root root 4096 Mar 30 06:40 ..\n-rw-r--r-- 1 root root 3106 Oct 22 2015 .bashrc\n-rw-r--r-- 1 root root 148 Aug 17 2015 .profile\ndrwx------ 2 root root 4096 Mar 25 07:51 .ssh"
  }
}
```

Tornado also does not support subset or batch functionality saltstack/salt#40476
Hook, local (both polling and standard running), and runners all appear to be fine.

**Comment by mchugh19** [comment]
Version 3.0 released which incorporates these fixes. The major version was bumped due to supporting saltapi with tornado, which caused changes to the returned output for both tornado and cherrypy. 

Pre-3.0 output
```
"return": [{
  "minionid": "Results and output"
}]
```

Output in 3.0
```
"Result": {
  "minionid": {
    "return": "Results and output"
  }
}
```
