### ISSUE TITLE
SaltAPI - Jenkins master/slave

### ISSUE THREAD

**Issue by idokaplan** [jenkinsci/saltstack-plugin#47]
Hi,

If I use "Restrict where this project can be run", is the connection to the SaltAPI server should be from the master of from the slave server?

Thanks!
Ido

**Comment by mchugh19** [comment]
If you restrict the build to a Jenkins slave the http requests to the salt api will be launched from that slave. You can verify by issuing a cmd.run to "echo {{NODE_NAME}}"

**Comment by idokaplan** [comment]
This is not working for me.
I will try to explain my infrastructure.
I have a master Linux server "JenkinsMaster" in location A.
I have a slave Linux server "JenkinsSlave" in location B.
I have a SaltAPI server "SaltAPI" in location B.

When I make a SaltAPI connection between "JenkinsMaster" to "SaltAPI", the connection is successful, I'm using the public IP of "SaltAPI" server because the servers are in different locations. 

When I make a SaltAPI connection between "JenkinsMaster" to "SaltAPI", when using "Restrict where this project can be run",  the connection is failed, I'm using the private IP of "SaltAPI" server because the servers are in the same locations. 

Can you please advise?

Thanks!
Ido

**Comment by chrisLeeTW** [comment]
I have some question with this topic.

my infrastructure as above.
I have a jenkins master & salt-api in one same server.
And I aslo one jenkin slave in another server with different private ip.

In my jenkins job, I did not "Restrict where this project can be run"
but salt Server Name is using "http://localhost:8000"
...... and I can make this job build success all the time, even it's run on salve XD.

this behavior did not match @mchugh19 you describe.

My Plugin version = 1.7.1 
Jenkins version = 2.37

Any idea ?
Thanks!

Chris

**Comment by mchugh19** [comment]
Okay, you are all correct. I've gotten back to this and will have to investigate how Jenkins handles agent offloading a bit.

**Comment by mchugh19** [comment]
Version 2.1.0 was just released and should resolve this issue. Please reopen if you have any problems.
