### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by idokaplan** [jenkinsci/saltstack-plugin#48]
Hi,

Is it possible to get an output of changes and errors only?

Thanks!
ido

**Comment by mchugh19** [comment]
Nope! But since you get the json or yaml output, you can parse it afterwards. 

In builds after 1.7.1 for example, you can select "none" output so that nothing is shown by default. You could then parse the SALTBUILDOUTPUT envvar and display the bits you wish.

**Comment by idokaplan** [comment]
SALTBUILDOUTPUT envvar is not working for me, I have opened an issue about this.
But if it will be fixed, do you have something that I can use?
I.E, if you already parse the SALTBUILDOUTPUT envvar, I will appreciate if you can share it. 

Thanks!
