### ISSUE TITLE
SALTBUILDOUTPUT

### ISSUE THREAD

**Issue by idokaplan** [jenkinsci/saltstack-plugin#49]
Hi,

I have created a second "execute shell" build step with "echo $SALTBUILDOUTPUT".
I get this output - 

[SaltTest] $ /bin/sh -xe /tmp/hudson5707637232705926996.sh

+ echo

Can you please help?

Thanks!
Ido

**Comment by mchugh19** [comment]
That's exactly how it works for me. 
```
Building in workspace /Users/mchughc/work/gits/saltstack-plugin/work/jobs/classic salt/workspace

[workspace] $ /bin/sh -xe /var/folders/b4/s7djtn515839jw5vbyjtw4r9cl4xp7/T/hudson4931263920961539038.sh
+ echo '[{"success":true}]'
[{"success":true}]
Finished: SUCCESS
```

Command is: `echo $SALTBUILDOUTPUT`

What version of the plugin are you running?

**Comment by idokaplan** [comment]
1.7.1

**Comment by idokaplan** [comment]
Hi,

Sorry for asking again.
Is there any update?

Thanks!
Ido

**Comment by mchugh19** [comment]
In poking around with this I am unable to replicate. Is there anything special about your Jenkins environment? Is this operation being done within a docker slave or anything? (Not that anything there should cause this to not work). Perhaps Selinux limits?

**Comment by idokaplan** [comment]
I'm closing this issue because I don't need to use this var for now.
Thanks!
