### ISSUE TITLE
fileserver.update

### ISSUE THREAD

**Issue by idokaplan** [jenkinsci/saltstack-plugin#51]
Hi,

Is it possible to run "salt-run fileserver.update"?

Thanks!
Ido

**Comment by mchugh19** [comment]
That should work just fine. Just use the runner client with the fileserver.update function.

```
Response on fileserver.update
[true]
Finished: SUCCESS
```

**Comment by idokaplan** [comment]
What is the "Target Type" and "Target"?

**Comment by mchugh19** [comment]
Target us unused for the runner type. So you can just enter any text and run the job. This UI issue is being addressed in the 2.0 release since it changes compatibility.

**Comment by idokaplan** [comment]
Nice, it's working.
Thanks.
