### ISSUE TITLE
saltstack-plugin reports jobs as failure even though everything indicates a success

### ISSUE THREAD

**Issue by rbjorklin** [jenkinsci/saltstack-plugin#55]
Just upgraded to 2.0.0 today and our runner jobs have started reporting failures even though everything looks fine. This is the messages we see:

    Building on master in workspace /var/lib/jenkins/workspace/Upgrade Organizations
    ERROR: One or more minion did not return code 0

As well as this at the very end:

        "retcode": 0
      }
    }]
    Build was aborted
    Finished: ABORTED

**Comment by mchugh19** [comment]
Oh no. Could you send over the debug output (as described on the [plugin wiki](https://wiki.jenkins-ci.org/display/JENKINS/saltstack-plugin#Logging%20Configuration))

I'll need to see what was submitted, and what was returned in order to figure out what's wrong. 

As a quick check, the 2.0 plugin changed the command line syntax to match the salt cli. Where previously you would use `arg1, arg2` you should now use `arg1 arg2` with spaces. If that wasn't updated, that would easily cause failures.

**Comment by rbjorklin** [comment]
This is what was submitted:

    Sending JSON: {"client":"runner","mods":"orch.application.host-upgrade-organizations","pillar":{"data":{"organizations":["customer"],"version":"3.33.5"}},"tgt":"","expr_form":"","fun":"state.orchestrate"}

The output on the other hand is ~3k lines when formatted properly and contains a little to much details... I guess I could try and anonymize it properly though. Regarding the splitting on spaces I'm aware of that but thanks for the pointer :)

**Comment by mchugh19** [comment]
Argh, I don't really want to look over 3k lines either ;)

Could you send over a simple example of the data structure that is returned? The [Utils.validateFunctionCall](https://github.com/jenkinsci/saltstack-plugin/blob/master/src/main/java/com/waytta/Utils.java#L144) is the bit that validates the return from the salt-api to see if it was successful. So I'd like to run the data structure through there to see what it is tripping up on. 

It could also be that there is a [string in the output](https://github.com/jenkinsci/saltstack-plugin/blob/2f62eed1a2188810f91c70f1c331f4bb676efe2d/src/main/java/com/waytta/Utils.java#L154-L156) that is being falsely detected as a salt error. So if the test case of the returned datastructure doesn't turn up anything, it would be good to know if you have "TypeError", " is not available.", or "ERROR" in the first object of the return.

The second bit of string checking is the only thing that should be new in the 2.0 release. So if something is getting falsely captured there, the validation can be tightened up.

**Comment by rbjorklin** [comment]
I cut it down to ~600 lines (hopefully without removing the important bits) and put it up on pastebin for 1 week. http://pastebin.com/kULuigXm

**Comment by mchugh19** [comment]
Just added that text to a file, added it to the test suite, and it passed just fine. So it sounds like the issue is in the other ~2400 lines :(

Not sure where to go next, but if you want to send me mail, we can transfer the full output out of band.

**Comment by mchugh19** [comment]
@rbjorklin Would you be willing to send over the full results from the salt-api return out of band?

**Comment by rbjorklin** [comment]
That could be arranged, where can I find contact details?

**Comment by mchugh19** [comment]
email: christian.mchugh@gmail.com

**Comment by mchugh19** [comment]
@rbjorklin any luck getting a version to email over? I'd really like to get this resolved for you.

**Comment by rbjorklin** [comment]
@mchugh19 Sorry about the delay, the job output has been sent to you after being anonymized.

**Comment by mchugh19** [comment]
Thanks for that! Version 2.1.0 was just released and should resolve this issue with tighter validation the saltapi return. Please reopen if you run into any further problems.
