### ISSUE TITLE
wait for completion always waits until timeout has been reached

### ISSUE THREAD

**Issue by rbjorklin** [jenkinsci/saltstack-plugin#56]
It seems using the "Wait for completion" checkbox makes jobs wait until the set timeout. On the other hand not using "Wait for completion" seems to successfully wait for completion. Something seems to be a little bit off?

The console output below is from when "wait for completion" was turned on.

    14:05:40 Running jid: 20170308130540775378
    14:05:43 Waiting for 1 minions
    14:05:43 0 minions are done
    14:05:43 Will check status every 10 seconds...
    14:05:55 Some minions returned. Waiting 600 seconds
    14:15:57 Response on state.sls application.host-app pillar='{"data":{"app":"application-admin","version":""}}' for apps.dev.example.com:

**Comment by mchugh19** [comment]
Right you are, fix developed. Will cut a point release shortly. Sorry for letting this get through

**Comment by mchugh19** [comment]
This was corrected in the just released 2.0.1. It could take up to a day for the update to be reflected in the jenkins plugin page.
