### ISSUE TITLE
minionTimeout should be global in Builds.java

### ISSUE THREAD

**Issue by chrisLeeTW** [jenkinsci/saltstack-plugin#59]
the current logic for local client with wait for completion in Builds.java will caused :

when there are some minions already done, 
and some are not, and they will run for much longer. 

in this siuation, We will change the "minionTimeout" setting in jenkins global configuration, which we thought this is a global timeout to a larger value.

and we thought plugin will continue poll job status with the interval of poll time which we defined in job configuration.

and then job will failed due to minionTimeout reached.

but actually plugin will directly wait for minionTimeout when not all minions had be done.

so it will wait for long time to job complete, even it will not take so much time for every time.

**Comment by mchugh19** [comment]
Greetings! I'm not completely clear on what you are requesting.

There are two timeouts:
1. The first, "poll time" controls how often jenkins will check in with the saltapi during a long running job. This can be set to something short (like 5 seconds) if you have a job that completes somewhat quickly. If you have a job that you know will run for an hour, checking every 5 seconds is a bit to frequent. In this case, you might want to have the saltapi plugin poll every minute or 5 minutes. The polltime is set at a global level in the Jenkins configuration screen. This value can be overwritten within the individual local job. That way if you have lots of short lived jobs, you can set the global poll time to something short. But for a single long running job, you are able to set a more sane setting on that single job. 

1. The second timeout, "Timeout", is set from the global Jenkins configuration screen. This value is new with the 2.0 release. If you have a job that should be run on multiple minions and only some minions return, this will set how long you will wait for the remaining minions to come back before assuming them offline and marking the build as a failure. This is helpful as without the timeout, the jenkins salt plugin will wait forever for the possibly non-existent minions to return. The default setting for the salt cli is 30 seconds. There was a bug in the 2.0 release where this timeout was always running. This activity was corrected with the 2.0.1 release.

It sounds like you may have been running into the minionTimeout bug from the 2.0 release. Does updating to 2.0.1 correct the behavior?

**Comment by chrisLeeTW** [comment]
Hi, mchugh19

Thanks for your explanation.

For first type timeout, It's very clear. What I confused it is the second type timeout.

With your current timeout design, for example.

I have a salt job which run on three minions. we notice that two minions will return fast, but one minion will run much longer maybe due to need for system provision for once.

So you can not always assumed this minion will run for such long time.

Based on the example, we may defined the timeout as bottom.

First type timeout = 10s
Second type timeout = 30mins (for once long run minions.)

As the result, we will wait for 30mins with high probability, or always wait for 30mins if average execution time is above the first type timeout.

**Comment by mchugh19** [comment]
How about if the plugin allows you to specify the minion timeout for the individual job as well? That way, for jobs where you expect that some minions might not return quickly, you can allow that in the job.

**Comment by mchugh19** [comment]
Version 2.1.0 was just released. The minionTimeout attribute is now able to be set per job. If you have any problems or questions feel free to re-open.
