### ISSUE TITLE
[Feature Request] Return state data back in yaml

### ISSUE THREAD

**Issue by gtmanfred** [jenkinsci/saltstack-plugin#6]
It would be awesome if the local, local_batch, and runner calls would actually request the data with 

`Accept: application/x-yaml`

So that we get a similar data format as we do when making these calls from the commandline.

Thanks
Daniel

**Comment by mchugh19** [comment]
That's doable! How do would you use it? Do you have something read the jenkins' console output, or is yaml just more intuitive for a human to parse since it's what you normally see?

**Comment by beardedeagle** [comment]
I second this, it would make the output much more intuitive as well as being native to SaltStack output.

**Comment by mchugh19** [comment]
Released with version 1.6. 

Note, since salt plugin needs to parse the output of salt-api, it still requests json output. The new config option merely allows outputting yaml to the jenkins console.
