### ISSUE TITLE
Question: saveEnvVar for pipeline

### ISSUE THREAD

**Issue by gattie** [jenkinsci/saltstack-plugin#74]
Looking over the code I've noticed that you have a saveEnvVar variable for the salt pipeline step, but it doesn't appear to be used in the performRequest method.

Is there a reason this bit isn't there for a pipeline step? With the Jenkins pipeline declarative syntax saving the output per your example:

```groovy
import groovy.json.*

node() {
  saltresult = salt authtype: 'pam', clientInterface: local(arguments: '"ls -la"', blockbuild: true,
    function: 'cmd.run', jobPollTime: 16, target: '*', targetType: 'glob'),
    credentialsId: 'a3d814c2-84ed-4752-94a8-271791bb5375', servername: 'http://localhost:8000'
  def prettyJson = JsonOutput.prettyPrint(saltresult)
  println(prettyJson)
}
```

result's in a syntax error, so it has to be wrapped in a script block like this:

```groovy
stage('Deploy to Test A Side') {
    when { branch "master" }
    steps {
        echo 'Deploying to Test...'
        script {
            saltresult = salt authtype: 'pam', clientInterface: local(arguments: "ls -la", blockbuild: true, function: 'cmd.run', target: '*', targetType: 'glob'), credentialsId: 'a3d814c2-84ed-4752-94a8-271791bb5375', servername: 'http://localhost:8000'
            def prettyJson = JsonOutput.prettyPrint(saltresult)
            println(prettyJson)
        }
    }
    post {
        failure {
            error("Build failed due to failed salt run")
        }
    }
}
```

which, for the most part works for me, but I was curious if it'd be possible to save the output using the saveEnvVar option, or some other method. I've been looking for the last day or so on the best ways of saving that output in a pipeline, specifically for the declarative pipeline DSL stuff, but wanted to get your take on it in case you've already been down that rabbit hole.

Thanks

**Comment by mchugh19** [comment]
The reason for not including the save EnvVar option is that the output of the pipeline job can be saved to a variable in groovy. As such, the envVar part is unnecessary. Likewise, groovy variables can be chopped and diced before use in the pipeline job, thus making the {{variable}} syntax to handle parameterized freestyle builds also unnecessary. Basically, with groovy available, you can now save the salt output, and further parse or filter as necessary, without needing the jenkins job to handle these special cases. 

It is really interesting that you need to wrap the pipeline task in a script. I have been testing with Jenkins 1.642 (the earliest pipeline capable build) and the given syntax works properly. What is the syntax error you get and what is the pipeline code used?

This works for me. Note that wrapping the salt pipeline in a node block is required. In this case, I'm running it on my agent1 agent, but it does need a build environment.
```
stage("run salt") {
    node("agent1") {
        saltresult = salt authtype: 'pam', clientInterface: local(arguments: '"sleep 5; tail -1 /etc/hosts"', blockbuild: true, minionTimeout: 32, function: 'cmd.run', jobPollTime: 7, target: '*', targetType: 'glob'), credentialsId: 'b5f40401-01b9-4b27-a5e8-8ae94bc90250', servername: 'http://localhost:8000'
        def prettyJson = JsonOutput.prettyPrint(saltresult)
        println(prettyJson)
    }
}
```

**Comment by gattie** [comment]
Yeah, the example you provided works for a plain groovy scripted pipeline. However, I am working with the Pipeline DSL aka Declarative Pipeline (https://jenkins.io/doc/book/pipeline/)

If I try to run that same stuff inside of a pipeline block with the pipeline DSL I get the following:

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 85: Expected a step @ line 85, column 17.
                   saltresult = salt authtype: 'pam', saveEnvVar: true, clientInterface: local(arguments: "ecm-api test", blockbuild: true, function: 'ecm.deploy',
                   ^

WorkflowScript: 87: Expected a step @ line 87, column 17.
                   def prettyJson = JsonOutput.prettyPrint(saltresult)
                   ^

2 errors

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:67)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:430)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:393)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:238)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
Finished: FAILURE
```

So, in order to get around this error, inside of a pipeline block you can write a script block that will essentially jump out of the Pipeline DSL and run plain groovy.

Per my example above, doing that works. Although, I do have to write that post block, which is sort of like a try catch block in a normal groovy pipeline, because if the salt run fails the entire pipeline doesn't stop there. It continues on running the rest of the pipeline but will set the overall status to FAILURE per [run.setResult(Result.FAILURE);](https://github.com/jenkinsci/saltstack-plugin/blob/7160ce07b6639a3023817f2a40fff5e756767ea9/src/main/java/com/waytta/SaltAPIStep.java#L223) in SaltAPIStep.java.

Back to the main question of saving the output within a pipeline block though. I've been searching through other plugins that save output within a Pipeline DSL block, but haven't found anything obvious on how to do it.

The Declarative Pipeline DSL stuff is pretty new and I haven't found good info on writing plugins to work seamlessly with it yet. It would be cool to save the output to a variable automatically though without writing the groovy like in your example.

So I guess my questions at this point are, do you think it's feasible to save the output to the SALTBUILDOUTPUT environment variable in a jenkins pipeline? Also, should a salt pipeline step stop the build if a failure occurs? It seems like the code just sets the build status to failure, but doesn't actually stop the build at that point.

**Comment by mchugh19** [comment]
Cool! I didn't even hear about the declarative pipeline syntax until this. Thanks!

Sounds like there are a couple of issues here:
1. Fail build immediately on error. Don't allow subsequent steps to run after plugin returns error
2. Support declarative pipeline syntax

Based on this ticket, a fix for 1 has been committed to master. Yay! 
As for number 2, I'm not sure what the proper course of action is. Running the salt pipeline without variable assignment works, but for that case, I'm not sure what the best way is to return the output. I've opened up a query on the mailing list: https://groups.google.com/forum/#!topic/jenkinsci-dev/FaD14fMb5Bw
I think expecting every plugin to handle environment variable processing is a bit of a hack. So I'd like to see how the community thinks this should be handled. In the short term, running the plugin with variable assignment and within a script block should keep you going.

**Comment by gattie** [comment]
Awesome, I will watch that thread on the mailing list as well as I am curious what the suggested way to handle that will be. Thanks for the info and quick responses.

**Comment by mchugh19** [comment]
Blamity! Master branch now allows saving salt-api output into a file. This should allow for declarative pipeline where you run the a salt pipeline without having to assign into a variable, and subsequent steps can then read or parse the saltOutput.json file as necessary. This should be in the next release.

**Comment by gattie** [comment]
Awesome! Thanks much.

I'll close this out as resolved.
