### ISSUE TITLE
[Feature Request]Supply an option to control whether executing 'run.setResult(Result.FAILURE)' 

### ISSUE THREAD

**Issue by fsfshijm** [jenkinsci/saltstack-plugin#77]
Currently, when salt command got an exception, 'saltstack-plugin' will set currentBuild.result to 'FAILURE':
SaltAPIBuilder.java:
```
try {
            success = perform(run, launcher, listener);
        } catch (SaltException e) {
            run.setResult(Result.FAILURE);
            throw new AbortException("Salt run failure: " + e);
        }
    	if (!success) {
    	    run.setResult(Result.FAILURE);
    	    throw new AbortException("Salt run failure");
    	}
```
Builds.java
```
                    if (timeoutFail) {
                        build.setResult(Result.FAILURE);
                        throw new SaltException(httpArray.getJSONObject(0).getJSONObject("Result").toString());
                    }
```

But, in my case, when I got an exception, I will also catch this exception, and then do something to make the pipeline pass; Meanwhile, I want to set 'currentBuild.result'='SUCCESS', but it's not workable due to   Jenkins mechanism: 'the result can only get worse':
```
    public void setResult(@Nonnull Result r) {
        if (state != State.BUILDING) {
            throw new IllegalStateException("cannot change build result while in " + state);
        }

        // result can only get worse
        if (result==null || r.isWorseThan(result)) {
            result = r;
            LOGGER.log(FINE, this + " in " + getRootDir() + ": result is set to " + r, LOGGER.isLoggable(Level.FINER) ? new Exception() : null);
        }
    }
```

So, I want to request a feature that 'saltstack-plugin' could supply an option to control whether executing 'run.setResult(Result.FAILURE)'

Thanks very much!

**Comment by mchugh19** [comment]
That's a good point. Should be able to just let let the plugin raise exceptions. 

Thanks!

**Comment by fsfshijm** [comment]
@mchugh19  Very glad to get your approval, looking forward to this features.

Thanks a lot!

**Comment by mchugh19** [comment]
This is now in the master branch as of pr #83 and will be in the next release.

**Comment by fsfshijm** [comment]
@mchugh19 Cool, thanks very much!

**Comment by mchugh19** [comment]
Version 3.0 released which incorporates these fixes. The major version was bumped due to supporting saltapi with tornado, which caused changes to the returned output for both tornado and cherrypy. 

Pre-3.0 output
```
"return": [{
  "minionid": "Results and output"
}]
```

Output in 3.0
```
"Result": {
  "minionid": {
    "return": "Results and output"
  }
}
```
