### ISSUE TITLE
[Feature Request]support retry mechanism when connection fails

### ISSUE THREAD

**Issue by fsfshijm** [jenkinsci/saltstack-plugin#84]
Salt command failed randomly, and will be success just by re-run the command. the error like this:
```
ERROR: Auth Error: net.sf.json.JSONException: JSONObject["return"] is not a JSONArray.

{"Error": "java.io.IOException: Server returned HTTP response code: 500 for URL: http://salt.dev.fwmrm.net/login
```
I thinks the reason should be some unstable services, like network, REST_CHERRYPY, ldap(we are using ldap to access the salt api service), it's almost impossible to fix this issue from the service side;

So, whether it's possible to support retry mechanism when creating the connection from saltstack-plugin side?, which will greatly  improve the stability of salt command.

Thanks very much!

**Comment by fsfshijm** [comment]
Maybe we can retry when 
```
            if (connection.getResponseCode() < 200 || connection.getResponseCode() > 299) {
```
?

**Comment by fsfshijm** [comment]
@mchugh19 Thank you very much for your quick response!
I saw your code, it just support retrying http connections when timeout, right? if the response code is 500, will not trigger retrying.

In my case, the response code is 500 with some unstable factors, whether we can retry when response code <200 or >299?

thanks.

**Comment by mchugh19** [comment]
We don't want jenkins to keep contacting the saltapi when the saltapi has correctly told us there is a problem, bad response, or auth issue.

With your 500 response, does running the same request later succeed? If so, the 500 check could be made retry'able.

**Comment by fsfshijm** [comment]
@mchugh19 Yes, for 500 error, it will succeed by re-run the same request

**Comment by mchugh19** [comment]
Cool cool. Retry on 500 added.

**Comment by mchugh19** [comment]
Version 3.0 released which incorporates these fixes. The major version was bumped due to supporting saltapi with tornado, which caused changes to the returned output for both tornado and cherrypy. 

Pre-3.0 output
```
"return": [{
  "minionid": "Results and output"
}]
```

Output in 3.0
```
"Result": {
  "minionid": {
    "return": "Results and output"
  }
}
```

**Comment by fsfshijm** [comment]
Got it, thanks very much!
