### ISSUE TITLE
'minionTimeout' is not workable if no minion returned

### ISSUE THREAD

**Issue by fsfshijm** [jenkinsci/saltstack-plugin#89]
minionTimeout is not workable if no minion returned; Use one minion as an example,  according to the code in 'runBlockingBuild' method
```
...
            // if minionTimeout is negative, still walkthrough the timeout process, but do not fail build
            boolean timeoutFail = true;
            if ( minionTimeout < 0) {
                timeoutFail = false;
                minionTimeout *= -1;
            }

            if (numMinionsDone > 0 && numMinionsDone < numMinions) {
                // Some minions returned, but not all
                // Give them minionTimeout to all return or fail build
                try {
...
```
Due to 'numMinionsDone > 0', when we just have one minion, the duration of which is long, then numMinionsDone will always be 0, 'minionTimeout' will not be used.

**Comment by mchugh19** [comment]
Right you are. The intended use case here was to catch unresponsive minions from the group of minions. This way you can have a long running job, but continue on (failing or not failing the build) after the timeout. If we were to use the minionTimeout as a job timeout, it would require everyone to know how long their job is expected to take, and explicitly set a larger value.

This does seem a little confusing, so perhaps the docs could be clarified. Or perhaps it just makes sense to make the minionTimeout a full job timeout. Hmmm, thoughts?

Also, the desired functionality can be accomplished with the timeout pipeline step
```
timeout(time: 30, unit: 'SECONDS') {
  salt ...
}
```

**Comment by fsfshijm** [comment]
@mchugh19 Thanks very much for your explanation, I think I got your point; 
'timeout pipeline step' works for me;
As we already have this 'timeout pipeline step' functionality, I think it's not very necessary to implement  a full job timeout in saltstack plugin separately, so for me,  I think that clarifying the docs is enough.

Thanks again.
