### ISSUE TITLE
Jenkins ENV variables in salt commands

### ISSUE THREAD

**Issue by rettink** [jenkinsci/saltstack-plugin#94]
Hi - Does this plugin support Jenkins environment variables in the salt commands? I tried using the $WORKSPACE and other variables but it and the others did not get interpolated. Thanks Tim

**Comment by mchugh19** [comment]
I think you are looking for the plugin's `{{variable}}` syntax. This is useful for evaluation of Jenkins parameters, and should also work for your workspace example. Click the ? next to the text fields for more information. 

The {{variable}} syntax was used to separate it from $VARIABLE as the latter might be in use for cmd.run lines to be evaluated on the destination host.

I'll close this for now, but if you have any problems or questions, feel free to re-open.
