### ISSUE TITLE
"Batch Wait" support ?

### ISSUE THREAD

**Issue by kedare** [jenkinsci/saltstack-plugin#97]
Hello,

Is there any plan to add a support for --batch-wait ?

Thanks :)

**Comment by mchugh19** [comment]
Looking into it. At first glance it appears that batch_wait may not be supported by the python api, and thus the netapi. Opened saltstack/salt#42225 to investigate

**Comment by kedare** [comment]
Hi again :)

Looks likke it is now supported, do you know if this is now supported by the Jenkins plugin ?
We moved to calling the salt command from the Jenkins job directly as we needed this feature but we are looking to use the plugin if this is possible.

Thanks

**Comment by mchugh19** [comment]
Support for batch_wait was just added to the master branch and will be in the next release.

**Comment by kedare** [comment]
Great, thanks :)

**Comment by mchugh19** [comment]
This was just released as part of the 3.2.0 release. It should be available within the next 24 hours.
