### ISSUE TITLE
java.lang.NullPointerException using Pipeline

### ISSUE THREAD

**Issue by anonymousobject** [jenkinsci/saltstack-plugin#98]
Hi, just discovered this plugin and I tested it on a freestyle job and got it to work fine with my Salt environment.  When I tried to implement the same Salt call in a Pipeline job, I cannot get it to work. 

I receive this output:

java.lang.NullPointerException
	at com.waytta.SaltAPIBuilder.getJID(SaltAPIBuilder.java:314)
	at com.waytta.SaltAPIStep$Execution.start(SaltAPIStep.java:226)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:224)
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:150)
        ...

My config is as follows:

stage('Deploy to server') {
        saltresult = salt authtype: 'pam', clientInterface: hook(post: '{something: true}', tag: 'salt/site/deploy'), credentialsId: 'salt-api-user', servername: 'https://salt.company.com:9090'
        println(saltresult)
}

I generated this config with the Pipeline snipper generator so I believe the syntax is correct. This same config also works in a freestyle job without issue.

Am I doing something wrong or is this a bug?

Thanks!

**Comment by mchugh19** [comment]
Totally a bug!

Should be fixed as of #100. Could you please test [3.1.1-beta1](https://github.com/jenkinsci/saltstack-plugin/releases/tag/v3.1.1-beta1) and confirm this corrects the problem? 

Thanks!

**Comment by anonymousobject** [comment]
Yes, it runs successfully now. Thanks!

**Comment by mchugh19** [comment]
Super. The fixed was released as 3.1.1 yesterday. You should see it hit the plugin mirrors over the next 24 hours.
