### ISSUE TITLE
2017.7 token url changed

### ISSUE THREAD

**Issue by tehsu** [jenkinsci/saltstack-plugin#99]
it looks like there were some changes in 2017.7.0 where the token url is generated is now /token instead of /login

**Comment by mchugh19** [comment]
/login appears to still function, but this does raise questions about the cherrypy api. I've raised an upstream ticket saltstack/salt#42491, and will update based on feedback.

**Comment by tehsu** [comment]
Interesting, if I use /login I get a 401, with /token I get the expected response and get a token.

**Comment by tehsu** [comment]
Here is the error that I get

FATAL: Bad ResponseCode: 500 Internal Server Error
HTTP ERROR: 
{"status": 500, "return": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py\", line 737, in hypermedia_handler\n    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)\n  File \"/usr/lib64/python2.7/site-packages/cherrypy/_cpdispatch.py\", line 60, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py\", line 1172, in POST\n    token=cherrypy.session.get('token')))\n  File \"/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py\", line 1068, in exec_lowstate\n    for i in ret:\n  File \"/usr/lib/python2.7/site-packages/salt/client/__init__.py\", line 547, in cmd_batch\n    salt.utils.warn_until(\nUnboundLocalError: local variable 'salt' referenced before assignment\n"}

**Comment by tehsu** [comment]
I downgraded CherryPy, I can get the expected response with /login now but same error as above.

**Comment by tehsu** [comment]
After some more testing, the above error only happens with local_batch.

**Comment by mchugh19** [comment]
Interesting! I suggest opening an issue with the salt project. They should
be able to help diagnose.

**Comment by tehsu** [comment]
I submitted it here, 

https://github.com/saltstack/salt/issues/42649

**Comment by tehsu** [comment]
Figured out that expr_form needs to be tgt_type for 2017.7.0

**Comment by mchugh19** [comment]
Support for tgt_type has been added to the master branch and will be included in the next release. As there is no way to detect the version of salt-api in use, it introduces a global config selection containing options of 2017.7+ and older.

**Comment by mchugh19** [comment]
The tgt_type update was released in the 3.2.0 plugin. It should be available within the next 24 hours. 

The Jenkins plugin now includes a global configuration option to determine the version of the saltapi in use. Currently it has to options, 2017.7 and older. The 2017.7 option updates the tgt_type key as well as enables some additional validation checking which was released in that version.
